// <auto-generated />
namespace Vera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _02_Add_FormingType_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02_Add_FormingType_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201612171332202_0.2_Add_FormingType_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
