// <auto-generated />
namespace Vera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _08_Add_Balance_to_Materials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08_Add_Balance_to_Materials));
        
        string IMigrationMetadata.Id
        {
            get { return "201703210825512_0.8_Add_Balance_to_Materials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
