// <auto-generated />
namespace Vera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _09_Add_Colorfulness_and_ColorfulnessPricePerFormat_entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09_Add_Colorfulness_and_ColorfulnessPricePerFormat_entities));
        
        string IMigrationMetadata.Id
        {
            get { return "201704141538279_0.9_Add_Colorfulness_and_ColorfulnessPricePerFormat_entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
