// <auto-generated />
namespace Vera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _011_Add_fields_to_Material_for_paper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_011_Add_fields_to_Material_for_paper));
        
        string IMigrationMetadata.Id
        {
            get { return "201706081828246_0.11_Add_fields_to_Material_for_paper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
