// <auto-generated />
namespace Vera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _07_Change_Format_Area_to_decimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07_Change_Format_Area_to_decimal));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141753166_0.7_Change_Format_Area_to_decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
