// <auto-generated />
namespace Vera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _06_Add_Material_and_MaterialType_entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06_Add_Material_and_MaterialType_entities));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141229487_0.6_Add_Material_and_MaterialType_entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
